version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abcd%4012345
      POSTGRES_DB: grocery_Booking_db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:Abcd12345@postgres:5432/grocery_booking_db?schema=public
    ports:
      - "3000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  postgres_data:
